language: c
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - ARCH=x86_64

script:
  - make CC=$CC

addons:
  apt:
    packages:
        - gcc-multilib

notifications:
    slack: dwarfoftherap:XvMGuDfbjzM8bvWTA1vEfPTK
